### ISSUE TITLE
custom links

### ISSUE THREAD

**Issue by georgetzlp** [ThePlasmaRailgun/cdn.dlcordapp.com#12]
is it possible to make it so you get redirected to any url you'd like? I've been trying to do it using the source code but no luck.

**Comment by NovaLogicDev** [comment]
So in order to redirect to a URL, the server accepts a second path `/attachments/shard<int:extra>/<path:cdn_content>` where the `extra` parameter allows the server to define more than one valid URL to redirect to. For example we can have a link such as `/atachments/shard1/<path:cdn_content>` which means the `extra` parameter is `1` and when we access our array of URLs the index of `1` returns `"https://www.reddit.com/r/YouFellForItFool/comments/cjlngm/you_fell_for_it_fool/"`

If you wanted to redirect to any meme you would need a way of storing which `extra` value is which link.
Of course on the frontend the problem is slightly different, you first have to accept any link that the user wants, you will have to determine a valid unused value for `extra` and then make the link as well as register the link to redirect to with the server via some sort of post request.

**Comment by georgetzlp** [comment]
> So in order to redirect to a URL, the server accepts a second path `/attachments/shard<int:extra>/<path:cdn_content>` where the `extra` parameter allows the server to define more than one valid URL to redirect to. For example we can have a link such as `/atachments/shard1/<path:cdn_content>` which means the `extra` parameter is `1` and when we access our array of URLs the index of `1` returns `"https://www.reddit.com/r/YouFellForItFool/comments/cjlngm/you_fell_for_it_fool/"`
> 
> If you wanted to redirect to any meme you would need a way of storing which `extra` value is which link.
> Of course on the frontend the problem is slightly different, you first have to accept any link that the user wants, you will have to determine a valid unused value for `extra` and then make the link as well as register the link to redirect to with the server via some sort of post request.

so you're saying it's not possible unless the dev makes it so you are able to do that, right?

**Comment by NovaLogicDev** [comment]
Yes, if you wanted to make it possible it would require a rather large change to both the html/js code and the backend python.

**Comment by georgetzlp** [comment]
alright I see thanks
